### ISSUE TITLE
Running into issues loading `phase.xml` due to CORS restriction

### ISSUE THREAD

**Issue by MarlonGamez** [jacoblister/noisefloor#2]
I'm able to build noisefloor, but unable to actually run it, as I run into the following when opening `build/js/noisefloor/index.html` in my browser.

```
noisefloor.js:122384 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
$global.FetchFile @ noisefloor.js:122384
noisefloor.js:122385 Access to XMLHttpRequest at 'file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/workspace/phase.xml' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
$global.FetchFile @ noisefloor.js:122385
noisefloor.js:122385 Failed to load resource: net::ERR_FAILED
$global.FetchFile @ noisefloor.js:122385
noisefloor.js:1610 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/workspace/phase.xml'.
    at $global.FetchFile (file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:122385:11)
    at Object.$packages.syscall/js.Value.ptr.Call (file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:41145:90)
    at Object.$packages.github.com/jacoblister/noisefloor/build/js/noisefloor.FS.ptr.Open (file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:122491:38)
    at Object.$packages.github.com/jacoblister/noisefloor/app/audiomodule/dsp.Engine.ptr.Load (file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:119745:24)
    at Object.App (file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:122192:23)
    at main (file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:122580:12)
    at $init (file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:122610:9)
    at $goroutine (file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:1601:19)
    at $runScheduled (file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:1647:7)
    at $schedule (file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:1671:5)
    at $go (file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:1633:3)
    at file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:122622:1
    at file:///Users/marlongamez/Projects/noisefloor/build/js/noisefloor/noisefloor.js:122625:4
index.html:20 web sleep...
index.html:22 done sleep
index.html:24 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
window.onload @ index.html:24
index.html:26 null
index.html:29 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
    at window.onload (index.html:29)
```

**Comment by jacoblister** [comment]
I've updated the README.md doc to use 'gopherjs serve', rather than opening the local file.  Above issue is caused by modern browsers blocking load of local filesystem content from javascript
